export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  RECIPES: '/recipes',
  FAVORITES: '/favorites',
  RECIPE_DETAIL: (slug: string) => `/recipes/${slug}`,
  RECIPE_EDIT: (slug: string) => `/myRecipes/${slug}/edit`,
  MY_RECIPES: '/myRecipes',
  RECIPE_NEW: '/myRecipes/new',
  KITCHEN: '/kitchen',
  ADD_INGREDIENTS: '/kitchen/addIngredients',
  SHOPPING_LIST: '/shoppingList',
  ADD_ELEMENTS: '/shoppingList/addElements',
  PLANNER: '/planner',
  NEW_PROMPT: '/planner/newPrompt',
  PROFILE: '/profile',
} as const;